### ISSUE TITLE
[Help] Custom admin taxonomy page view and cmb2 fields

### ISSUE THREAD

**Issue by pgroot91** [CMB2/CMB2-Snippet-Library#98]
Hi Guys, 

I need some directions/advice/guidance here. 

Currently forked a part of a project and want to add some extra fields to a custom admin view taxonomy page. Now i want to add a couple of cmb2 field including one for uploading an image and some additional text type fields. 

See: https://github.com/barrykooij/wp-car-manager/blob/master/assets/views/page/makes.php

Is there by any change code snippets are available that point me in the right direction to archive the following. Or could someone advice me a trustworthly developer(paid) that can help me out here?

**Comment by tw2113** [comment]
In terms of just outputting some fields, I have to imagine that some of the snippets from https://github.com/CMB2/CMB2-Snippet-Library/tree/master/front-end would work. Just need to modify potentially for admin-based. One caveat though may be that they get their own submit button, instead of integrating with whatever save button you already have on that view.

Not sure how much flexibility you have with this, but it may be worth just recreating everything as a CMB2 options page as well.

**Comment by pgroot91** [comment]
@tw2113 thanks for your reaction! We will soon try to work this out and let you know if we manage to make things work 👍

**Comment by pgroot91** [comment]
Got this solved by following some online tutorials! (not using cmb2 in this case)
